# Generated by Django 4.0 on 2024-01-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_recommendedcourse_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourse',
            name='analysis',
            field=models.TextField(null=True),
        ),
    ]
