# Generated by Django 4.0 on 2024-01-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_recommendedcourse_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='cet_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predresults',
            name='gpa_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
