# Generated by Django 4.0 on 2024-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_predresults_cet_status_predresults_gpa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predresults',
            name='cet_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='gpa_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
