# Generated by Django 4.0 on 2024-02-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_predresults_cet_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='cet_status',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='gpa_status',
        ),
    ]
