# Generated by Django 4.0 on 2024-02-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_predresults_cet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedcourse',
            name='cet_status',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='recommendedcourse',
            name='gpa_status',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
